from __future__ import annotations

from .models import Scenario


def load_default_scenarios() -> list[Scenario]:
    return [
        Scenario(
            scenario_id="flask-avatar-localhost",
            framework="Flask",
            route="/api/avatar/fetch",
            method="POST",
            purpose="Fetch a remote avatar for a user profile",
            target_url="http://127.0.0.1:8080/admin",
            source_parameter="avatar_url",
            user_supplied=True,
            user_role="authenticated_user",
            outbound_client="requests",
            accepts_redirects=True,
            dns_resolution=["127.0.0.1"],
            allowlisted_hosts=[],
            code_excerpt='image = requests.get(request.json["avatar_url"], timeout=3)',
            env_tags=["user-driven-fetch"],
            required_repairs=["scheme_allowlist", "private_range_block", "host_allowlist", "disable_redirects"],
            expected_action="block",
            risk_notes="Direct loopback target from a profile helper.",
        ),
        Scenario(
            scenario_id="express-webhook-metadata",
            framework="Express",
            route="/admin/webhook/test",
            method="POST",
            purpose="Let operators test webhook delivery",
            target_url="http://169.254.169.254/latest/meta-data/",
            source_parameter="callbackUrl",
            user_supplied=True,
            user_role="admin",
            outbound_client="axios",
            accepts_redirects=True,
            dns_resolution=["169.254.169.254"],
            allowlisted_hosts=[],
            code_excerpt='const response = await axios.get(req.body.callbackUrl);',
            env_tags=["admin-surface", "customer-controlled-destination"],
            required_repairs=["private_range_block", "host_allowlist", "disable_redirects", "egress_acl"],
            expected_action="block",
            risk_notes="Metadata endpoint reachable from a testing helper.",
        ),
        Scenario(
            scenario_id="django-import-file-scheme",
            framework="Django",
            route="/integrations/import",
            method="POST",
            purpose="Import a remote partner manifest",
            target_url="file:///etc/passwd",
            source_parameter="source_url",
            user_supplied=True,
            user_role="staff_user",
            outbound_client="requests",
            accepts_redirects=False,
            dns_resolution=[],
            allowlisted_hosts=[],
            code_excerpt='manifest = requests.get(request.POST["source_url"], timeout=5)',
            env_tags=["staff-surface"],
            required_repairs=["scheme_allowlist"],
            expected_action="block",
            risk_notes="Non-HTTP scheme should be denied before any network access.",
        ),
        Scenario(
            scenario_id="fastapi-cdn-image-allow",
            framework="FastAPI",
            route="/images/cache",
            method="POST",
            purpose="Mirror a marketing banner from a managed CDN",
            target_url="https://cdn.example.com/assets/banner.png",
            source_parameter="image_url",
            user_supplied=True,
            user_role="editor",
            outbound_client="httpx",
            accepts_redirects=False,
            dns_resolution=["8.8.8.8"],
            allowlisted_hosts=["cdn.example.com"],
            code_excerpt='safe_url = validate_outbound_url(payload.image_url)\nasync with httpx.AsyncClient(follow_redirects=False) as client:\n    resp = await client.get(safe_url)',
            env_tags=["cdn-only", "egress-allowlist", "allowlisted-destination"],
            required_repairs=[],
            expected_action="allow",
            risk_notes="Approved CDN path with URL validation already present.",
        ),
        Scenario(
            scenario_id="django-partner-feed-allow",
            framework="Django",
            route="/sync/partner-feed",
            method="POST",
            purpose="Sync a signed feed from a contracted partner",
            target_url="https://api.partner.example/v1/feed",
            source_parameter="partner_url",
            user_supplied=False,
            user_role="service_account",
            outbound_client="requests",
            accepts_redirects=False,
            dns_resolution=["1.1.1.1"],
            allowlisted_hosts=["api.partner.example"],
            code_excerpt='partner_url = settings.TRUSTED_PARTNER_URL\nresponse = requests.get(partner_url, timeout=5)',
            env_tags=["contracted-partner", "egress-allowlist"],
            required_repairs=[],
            expected_action="allow",
            risk_notes="Static partner URL, signed upstream, and network controls in place.",
        ),
        Scenario(
            scenario_id="express-preview-localhost",
            framework="Express",
            route="/preview/render",
            method="POST",
            purpose="Render a remote preview for a pasted URL",
            target_url="http://localhost:3000/debug",
            source_parameter="previewUrl",
            user_supplied=True,
            user_role="authenticated_user",
            outbound_client="axios",
            accepts_redirects=True,
            dns_resolution=["127.0.0.1"],
            allowlisted_hosts=[],
            code_excerpt='const html = await axios.get(req.body.previewUrl, { maxRedirects: 5 });',
            env_tags=["user-driven-fetch"],
            required_repairs=["private_range_block", "host_allowlist", "disable_redirects", "egress_acl"],
            expected_action="block",
            risk_notes="Open preview endpoint can pivot into localhost services.",
        ),
        Scenario(
            scenario_id="fastapi-tenant-crawler-internal-dns",
            framework="FastAPI",
            route="/tenants/{tenant_id}/crawl",
            method="POST",
            purpose="Crawl a customer-provided URL for preview metadata",
            target_url="http://api.customer.internal/report",
            source_parameter="seed_url",
            user_supplied=True,
            user_role="tenant_admin",
            outbound_client="httpx",
            accepts_redirects=False,
            dns_resolution=["10.12.4.8"],
            allowlisted_hosts=[],
            code_excerpt='async with httpx.AsyncClient() as client:\n    resp = await client.get(payload.seed_url)',
            env_tags=["multi-tenant", "customer-controlled-destination"],
            required_repairs=["private_range_block", "host_allowlist", "dns_rebind_guard", "egress_acl"],
            expected_action="block",
            risk_notes="Internal DNS name resolves into a tenant-adjacent private subnet.",
        ),
        Scenario(
            scenario_id="spring-redis-gopher-block",
            framework="Spring Boot",
            route="/ops/relay",
            method="POST",
            purpose="Relay a URL for an operations dry run",
            target_url="gopher://127.0.0.1:6379/_PING",
            source_parameter="relayUrl",
            user_supplied=True,
            user_role="ops_user",
            outbound_client="WebClient",
            accepts_redirects=False,
            dns_resolution=["127.0.0.1"],
            allowlisted_hosts=[],
            code_excerpt='webClient.get().uri(request.relayUrl()).retrieve().bodyToMono(String.class);',
            env_tags=["ops-surface"],
            required_repairs=["scheme_allowlist", "private_range_block", "egress_acl"],
            expected_action="block",
            risk_notes="Non-HTTP scheme plus loopback Redis port.",
        ),
        Scenario(
            scenario_id="flask-screenshot-review",
            framework="Flask",
            route="/capture/page",
            method="POST",
            purpose="Capture a screenshot of a user-supplied page",
            target_url="https://news.example.net/article/42",
            source_parameter="target_url",
            user_supplied=True,
            user_role="authenticated_user",
            outbound_client="requests",
            accepts_redirects=True,
            dns_resolution=["9.9.9.9"],
            allowlisted_hosts=[],
            code_excerpt='page = requests.get(payload["target_url"], allow_redirects=True, timeout=3)',
            env_tags=["user-driven-fetch"],
            required_repairs=["host_allowlist", "disable_redirects", "dns_rebind_guard"],
            expected_action="review",
            risk_notes="External target is not obviously malicious but the feature needs tighter controls.",
        ),
        Scenario(
            scenario_id="express-callback-review",
            framework="Express",
            route="/callbacks/verify",
            method="POST",
            purpose="Validate a customer callback endpoint before activation",
            target_url="https://customer-callback.example/hook",
            source_parameter="callbackUrl",
            user_supplied=True,
            user_role="tenant_admin",
            outbound_client="axios",
            accepts_redirects=False,
            dns_resolution=["8.8.4.4"],
            allowlisted_hosts=[],
            code_excerpt='const probe = await axios.get(req.body.callbackUrl, { timeout: 2000 });',
            env_tags=["customer-controlled-destination", "multi-tenant"],
            required_repairs=["host_allowlist", "dns_rebind_guard", "timeout_body_cap"],
            expected_action="review",
            risk_notes="External callback stays public but still needs bounded verification and tenancy-aware allowlisting.",
        ),
        Scenario(
            scenario_id="fastapi-s3-presigned-allow",
            framework="FastAPI",
            route="/models/fetch",
            method="POST",
            purpose="Fetch a model artifact from a pre-signed bucket URL",
            target_url="https://public-bucket.s3.amazonaws.com/model.bin?X-Amz-Signature=test",
            source_parameter="artifact_url",
            user_supplied=False,
            user_role="service_account",
            outbound_client="httpx",
            accepts_redirects=False,
            dns_resolution=["8.8.8.8"],
            allowlisted_hosts=["public-bucket.s3.amazonaws.com"],
            code_excerpt='safe_url = validate_outbound_url(job.artifact_url)\nresp = await client.get(safe_url)',
            env_tags=["egress-allowlist", "signed-request", "allowlisted-destination"],
            required_repairs=[],
            expected_action="allow",
            risk_notes="Pre-signed object store URL from a controlled job pipeline.",
        ),
        Scenario(
            scenario_id="nextjs-og-image-allow",
            framework="Next.js API Route",
            route="/api/social-card",
            method="POST",
            purpose="Fetch a trusted background image for OG card rendering",
            target_url="https://images.example-cdn.net/social/card.png",
            source_parameter="backgroundUrl",
            user_supplied=True,
            user_role="editor",
            outbound_client="fetch",
            accepts_redirects=False,
            dns_resolution=["1.0.0.1"],
            allowlisted_hosts=["images.example-cdn.net"],
            code_excerpt='const url = await validateOutboundUrl(req.body.backgroundUrl);\nconst resp = await fetch(url, { redirect: "manual" });',
            env_tags=["cdn-only", "egress-allowlist", "allowlisted-destination"],
            required_repairs=[],
            expected_action="allow",
            risk_notes="Explicit validation and manual redirect handling already exist.",
        ),
        Scenario(
            scenario_id="django-invoice-internal-ip",
            framework="Django",
            route="/finance/render-preview",
            method="POST",
            purpose="Render an invoice preview from a supplier URL",
            target_url="http://10.0.8.15:8080/render",
            source_parameter="render_url",
            user_supplied=True,
            user_role="finance_user",
            outbound_client="requests",
            accepts_redirects=False,
            dns_resolution=["10.0.8.15"],
            allowlisted_hosts=[],
            code_excerpt='preview = requests.get(form.cleaned_data["render_url"], timeout=4)',
            env_tags=["user-driven-fetch"],
            required_repairs=["private_range_block", "host_allowlist", "dns_rebind_guard", "egress_acl"],
            expected_action="block",
            risk_notes="Direct RFC1918 hit from a supplier preview helper.",
        ),
        Scenario(
            scenario_id="flask-redirect-broker-block",
            framework="Flask",
            route="/broker/probe",
            method="POST",
            purpose="Probe a broker URL before storing it for later fetches",
            target_url="https://trusted-broker.example/redirect?next=http://127.0.0.1:9000/health",
            source_parameter="broker_url",
            user_supplied=True,
            user_role="staff_user",
            outbound_client="requests",
            accepts_redirects=True,
            dns_resolution=["8.8.8.8"],
            allowlisted_hosts=["trusted-broker.example"],
            code_excerpt='response = requests.get(payload["broker_url"], allow_redirects=True, timeout=2)',
            env_tags=["allowlisted-destination"],
            required_repairs=["disable_redirects", "redirect_validation", "dns_rebind_guard"],
            expected_action="block",
            risk_notes="Open redirect on an approved broker can still land on localhost.",
        ),
    ]
